

spring:
  application.name: http-fileupload-source
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      #          configuration:
      #            value.deserializer: com.thinateh.stream.scslogging.PersonDeserializer
      bindings:
        upload-output:
          destination: output
        supply-out-0:
          destination: input
        #        transformtrim-in-0:
        #          destination: input
        #          group: transformer
        #          consumer:
        #            properties:
        #              value.deserializer: com.thinateh.stream.scslogging.PersonDeserializer
        #        transformtrim-out-0:
        #          destination: output
        log-in-0:
          group: log
          destination: input,output
      function:
        bindings:
          transform|trim-in-0: input
          transform|trim-out-0: output
  kafka:
    bootstrap-servers: ${spring.cloud.stream.kafka.binder.brokers}
    #producer:
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: com.thinatech.scs.UploadSerializer

upload:
  tmp-directory: /tmp/uploads
  parts:
    - file
    - config
